version: '3'

services:
  next-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: free-manga-web
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    # ホットリロードを有効化
    command: npm run dev
    # 既存のモックAPIネットワークに接続
    networks:
      - default
      - free-manga-backend_default

networks:
  free-manga-backend_default:
    external: true