version: '3'

services:
  next-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: free-manta-web
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - API_INTERNAL_URL=http://prism-mock:4010
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:4010
    # ホットリロードを有効化
    command: npm run dev
    # 既存のモックAPIネットワークに接続
    networks:
      - default
      - free-manga-apimock_default

networks:
  free-manga-apimock_default:
    external: true